import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import dynamic from 'next/dynamic';
import CreatePost from '@/components/createPost';
import CreateProfile from '@/components/createProfile';
import ListCard from '@/components/ListCard';
import { useData } from '@/hooks/useData';
import CreateDomain from '@/components/createDomain';
import TransferDomain from '@/components/transferDomain';
import BadgeComponent from '@/components/badgeComponent';
import CreateReaction from '@/components/createReaction';

const WalletMultiButtonDynamic = dynamic(
  async () => (await import('@solana/wallet-adapter-react-ui')).WalletMultiButton,
  { ssr: false },
);

function Home() {
    const { userDomainList, profilesList, postsList, issuerList, refreshData } = useData();

    // DgpTGt1CJsJRGzfzvcgJ93panPf2cRZLNkakJ4wpTwta is the TLD for .gum domains on devnet
    const renderDomainCard = (domain: any, index: any) => (
        <div key={index} className={styles.userCard}>
            <div className={styles.userNumber}>{index + 1}</div>
            <div className={styles.userInfo}>
                <p className={styles.userEmail}>Domain: {domain.name}{domain.domain === "DgpTGt1CJsJRGzfzvcgJ93panPf2cRZLNkakJ4wpTwta" ? ".gum" : ""} </p> 
            </div>
        </div>
    );

    const renderProfileCard = (profile: any, index: any) => (
        <div key={index} className={styles.userCard}>
            <div className={styles.userNumber}>{index + 1}</div>
            <div className={styles.userInfo}>
                <p className={styles.userEmail}>Profile Account: {profile.address}</p>
            </div>
        </div>
    );

    const renderPostCard = (post: any, index: any) => (
        <div key={index} className={styles.userCard}>
            <div className={styles.userNumber}>{index + 1}</div>
            <div className={styles.userInfo}>
                <p className={styles.userEmail}>Post Account: {post.address}</p>
                <p className={styles.userAuthority}>Profile Account: {post.profile}</p>
                <p className={styles.userAuthority}>MetadataUri: {JSON.stringify(post.metadata_uri)}</p>
            </div>
        </div>
    );
    
    return (
        <>
        <Head>
            <title>Gum App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <div className={styles.leftContainer}>
            <div className={styles.walletButtons}>
                <WalletMultiButtonDynamic />
            </div>
            <div className={styles.componentContainer}>
                <CreateDomain />
            </div>
            <div className={styles.componentContainer}>
                <TransferDomain />
            </div>
            <div className={styles.componentContainer}>
                <CreateProfile />
            </div>
            <div className={styles.componentContainer}>
                <CreatePost onPostCreated={refreshData} />
            </div>
            <div className={styles.componentContainer}>
                <CreateReaction />
            </div>
            </div>
            <div className={styles.rightContainer}>
                <ListCard title="Your Domain Accounts" list={userDomainList} renderItem={renderDomainCard} />
                <ListCard title="Your Profile Accounts" list={profilesList} renderItem={renderProfileCard} />
                <ListCard title="Your Post Accounts" list={postsList} renderItem={renderPostCard} />
            </div>
        </main>
        </>
    );
}

export default Home;